---

- name: "Including distro-specific variables"
  include_vars: "vars_{{ ansible_distribution }}.yml"

- name: "Setting things up for {{ ansible_distribution }}"
  include: "setup_{{ ansible_distribution }}.yml"
  when: ansible_distribution in [ 'Ubuntu', 'Gentoo' ]

- name: "Ensuring /etc/nginx/snippets/mage_responses.conf"
  template:
    src: "nginx-snippets/mage_responses.conf"
    dest: "/etc/nginx/snippets/mage_responses.conf"
    mode: 0644
  notify: 
    - reload nginx

- name: "Ensuring /etc/nginx/snippets/mage_php.conf"
  template:
    src: "nginx-snippets/mage_php.conf"
    dest: "/etc/nginx/snippets/mage_php.conf"
    mode: 0644
  notify: 
    - reload nginx

- name: "Ensuring a correctly configured default site definition file is provided."
  template:
    src: default.j2
    dest: "/etc/nginx/sites-available/default"
    mode: 0644
    owner: root
    group: root
  notify:
    - reload nginx